version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
       - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080

volumes:
  mysql-data:
